language: node_js

node_js:
  - "12"

cache:
  directories:
  - TP1-2021

deploy:
  provider: pages
  skip_cleanup: true
  edge: true
  github_token: $github_token
  local_dir: TP1-2021
  commit_message: "Deploy Release"
  on:
    branch: master  